# Generated by Django 4.1.2 on 2022-12-12 12:20

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
